### PR TITLE
Add timestamp to rinkeby genesis params

### PR DESCRIPTION
**Pull request by vpulim**
Currently, an incorrect hash is computed on the rinkeby genesis block since the timestamp field is missing. This PR adds the timestamp field to the genesis params.

Please release as ``0.4.1`` after merging since https://github.com/ethereumjs/ethereumjs-block/pull/52 depends on this.

### CODE REVIEW

**Comment by holgerd77** [comment]
Is this only for PoA chains? The other genesis definitions also doesn't contain this field. (?)

**Comment by holgerd77** [comment]
Respectively could you check if I forgot the others too?

**Comment by vpulim** [comment]
Only rinkeby requires the timestamp field so you won't find it in the other definitions. However, in order to fully support all genesis state possibilities we would need to allow the following fields:

``nonce, difficulty, coinbase, timestamp, parentHash, extraData and gasLimit, timestamp, mixhash``

In the future, it would be useful to allow Common to support custom genesis state definitions so the library can support private networks.

The test cases cover mainnet, rinkeby and ropsten so those all have correct definitions now (after the change made in this PR). The kovan genesis hash is still broken but I wasn't able to find much information about it and thus couldn't figure out why it isn't hashing properly.

**Comment by holgerd77** [comment]
1. Should we add a timestamp field with null to the other networks to make this more explicit?

2. Can you open an issue for private network support?

**Comment by vpulim** [comment]
@holgerd77 Added timestamps to the other networks and opened a [new issue](https://github.com/ethereumjs/ethereumjs-common/issues/22)

**Comment by holgerd77** [comment]
Ok, have released this as [v0.4.1](https://github.com/ethereumjs/ethereumjs-common/releases/tag/v0.4.1).

**Pull request merged**
