### PR TITLE
Run gh actions on PR

### PR DESCRIPTION
**Pull request by ryanio**
Accidentally missed running gh actions on `pull_request`, so this adds it.

### CODE REVIEW

**Comment by holgerd77** [comment]
Can you rebase this and submit the PR from an up-to-date `master` branch?

**Comment by evertonfraga** [comment]
AFAICT, the “Rebase and merge” option should be enough.

**Comment by holgerd77** [comment]
@evertonfraga Hmm, I've never used this and am a bit afraid. Are the tests actually run again after the rebase happened? If not then we otherwise have a corrupted `master` branch if something goes wrong on rebase?

**Comment by ryanio** [comment]
@holgerd77  I just rebased 👍

> @evertonfraga Hmm, I've never used this and am a bit afraid. Are the tests actually run again after the rebase happened? If not then we otherwise have a corrupted `master` branch if something goes wrong on rebase?

I believe the actions would run again on master since the actions are triggered on push.

**Pull request merged**
