### PR TITLE
Fix mainnet bootnodes

### PR DESCRIPTION
**Pull request by PhilippLgh**
updates mainnet bootstrap node according to
https://github.com/ethereum/go-ethereum/blob/master/params/bootnodes.go

### CODE REVIEW

**Comment by ryanio** [comment]
Just a note, @evertonfraga is currently migrating this package to https://github.com/ethereumjs/ethereumjs-vm/tree/master/packages/common, so I'm not sure if this PR is best applied here or there.

**Comment by evertonfraga** [comment]
Send it there, please @philipplgh!

This repo will be archived no later than end of this week.

**Comment by holgerd77** [comment]
Sorry, my fault, linked the repo here out of habit. 🙄

**Comment by holgerd77** [comment]
@PhilippLgh Can you eventually then directly add the bootnodes for the other networks, so `Ropsten`, `Rinkeby` and `Goerli` (eventually you can even have a short look at Kovan)? Then it would be worth to directly do a short patch release on this.

**Comment by PhilippLgh** [comment]
sounds good 👍

**Comment by evertonfraga** [comment]
Closing, as this needs to be reopened in https://github.com/ethereumjs/ethereumjs-vm.

**Pull request closed without merging**
