### PR TITLE
New release v1.3.2

### PR DESCRIPTION
**Pull request by holgerd77**

### CODE REVIEW

**Comment by s1na** [comment]
Thanks for merging the PR Holger. Can we wait however till tomorrow before doing the release? I was planning to make a PR for EIP-2200's gas parameters first thing tomorrow

**Comment by holgerd77** [comment]
Yeah, sure.

**Comment by holgerd77** [comment]
Will then rebase and add the other changes as well.

**Comment by holgerd77** [comment]
@s1na This is now ready for re-review.

**Comment by holgerd77** [comment]
Just published as [v1.3.2](https://github.com/ethereumjs/ethereumjs-common/releases/tag/v1.3.2).

**Pull request merged**
